name: homecareapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  lottie: ^2.0.0
  dio: ^4.0.6
  rating_dialog: ^2.0.4
  shared_preferences: ^2.0.15
  http: ^0.13.3
  provider: ^6.0.4
  image_picker: ^0.8.4+4
  path_provider: ^2.0.11
  permission_handler: ^10.2.0

  cupertino_icons: ^1.0.2
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  